"""add relationship

Revision ID: 17fb01bccfb2
Revises: 7c7671960353
Create Date: 2020-01-06 16:26:22.878863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fb01bccfb2'
down_revision = '7c7671960353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(length=30), nullable=False, unique=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_tag',
    sa.Column('feed_id', sa.BigInteger(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_tag')
    op.drop_table('tags')
    # ### end Alembic commands ###
