"""init

Revision ID: 7c7671960353
Revises: 
Create Date: 2020-01-06 14:39:29.095516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7671960353'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('login_type', sa.Unicode(length=20), nullable=False),
    sa.Column('access_token', sa.Unicode(length=255), nullable=False),
    sa.Column('refresh_token', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('image', sa.Unicode(length=255), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('url', sa.Unicode(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeds')
    op.drop_table('users')
    # ### end Alembic commands ###
