"""add avatar_url

Revision ID: 9674f86fee05
Revises: f8dfd35a9c3f
Create Date: 2020-01-09 17:10:53.179790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9674f86fee05'
down_revision = 'f8dfd35a9c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.Unicode(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
