"""add nickname to user

Revision ID: f8dfd35a9c3f
Revises: 17fb01bccfb2
Create Date: 2020-01-06 19:26:10.300109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8dfd35a9c3f'
down_revision = '17fb01bccfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tags', ['name'])
    op.add_column('users', sa.Column('nickname', sa.Unicode(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    op.drop_constraint(None, 'tags', type_='unique')
    # ### end Alembic commands ###
